### PR TITLE
Fixing squid:ForLoopCounterChangedCheck  for loop stop conditions should be invariant fix 2

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:ForLoopCounterChangedCheck - “"for" loop stop conditions should be invariant”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:ForLoopCounterChangedCheck
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by gallandarakhneorg** [comment]
Please install the checkstyle plugin in your IDE, or run Maven on the command-line for fixing the problems before submitting the PR, and obtain a broken PR.

**Comment by devFozgul** [comment]
OK. I will do that in the shortest possible time.

**Comment by devFozgul** [comment]
I have installed 6.18 version of IntelliJ Idea checkstyle plugin. But
somehow, I get exception while adding your checkstyle.xml as a parameter.
It gives me  loading exception error. Anyhow I will also ask my colleagues
if they have some info about it.

**Comment by gallandarakhneorg** [comment]
This is the correct version of checkstyle. The Checkstyle configuration needs to define the global properties:
* ${mainbasedir}: the path to the folder where the root pom.xml is located
* ${checkstyleheaderdir}: the path to the folder where the header template is located, usually `${mainbasedir}/checkstyle/src/main/resources/org/arakhne/afc/checkstyle` (with Unix path name standard)

These variables are automatically computed by Maven on the command-line, but not in the IDEs (since the Groovy maven plugin is ignored).

**Comment by devFozgul** [comment]
Thank you for the direction you have given me. With the correct "headerdir", I could add the xml file now. What do I expect now? Will the IDE give me a warning in real-time or I need to have a look in the warnings list or something like that?

**Comment by gallandarakhneorg** [comment]
I don't know how the checkstyle plugin is working on IntelliJ. On the 
Eclipse IDE, the plugin is checking a file and put errors in the editor 
each time the file is saved.

Stéphane.

**Pull request merged**
