### PR TITLE
Fixing squid: S1192 String literals should not be duplicated 

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1192 - “String literals should not be duplicated”. 
This PR will reduce 120 min TD.
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1192
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by gallandarakhneorg** [comment]
Please use the i18n standard for coding the string literals. See the rest of the AFC code for examples.

**Comment by devFozgul** [comment]
I wonder why you closed this. I could modify it according to the i18n
standard after seeing the examples.

**Comment by devFozgul** [comment]
Could you please give me a few good examples of  the  files in which  I can
find examples of the standard? Thank you.

**Comment by gallandarakhneorg** [comment]
Example: https://github.com/gallandarakhneorg/afc/blob/master/core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/Path2afp.java#L109

The string `E1` is a valid in-code string (note the NON-NLS comment at the end of the line) that is the ID of the message in the `Path2afp.properties` file.

Please configure your Sonar for avoiding to have squid:S1192 when NON-NLS comment is present.

**Comment by devFozgul** [comment]
Ok. I would like to ask before I prepare a PR on  an issue, namely  squid:
S2975  '"clone" should not be used';  meaning a copy constructor should be
used instead... There are quite a few places in the project with cloning
used. Would you be interested in my converting them to copy constructor?

**Comment by gallandarakhneorg** [comment]
**Don't remove clones.**
But you could add copy-constructors. Don't forget to do a deep copy in the copy-constructors (that is the meaning of the clones).
We are providing the two features since the AFC library may be used with one or the other approach by the AFC users. Additionally, clone may be faster that copy-constructors since it is a "low-level" copy of the memory.

**Comment by devFozgul** [comment]
OK.

**Comment by devFozgul** [comment]
Moving to another rule squid: S1168  "empty arrays and collections should
be returned instead of null". May  I convert the null returns to empty
arrays and collections?

**Comment by gallandarakhneorg** [comment]
I'm almost agree with S1168. If you do, don't create new instances of collections but use the `Collections` utilities for creating the empty array/collections.

**Comment by devFozgul** [comment]
Ok. That is What I intended doing... Using the Collections library
available. If there are tests AssertNull for those outputs, also those
tests will be modified accordingly. Because we are not returning null
anymore but an object but empty object.

**Comment by devFozgul** [comment]
I have just cloned a fresh version of the project. But I have 6  compiler
errors like "Error:(62, 39) java: type argument ? extends V is not within
bounds of type-variable RV" resulting from
core\math\src\main\java\org\arakhne\afc\math\extensions\xtext\Tuple2DExtensions.java
 class.  Do you know what might be the reason?

**Comment by gallandarakhneorg** [comment]
Are you using Maven for compiling? Are you using JDT/ECJ?

**Comment by devFozgul** [comment]
I am using maven. What are the others. Previously I was not getting these
errors.

**Comment by gallandarakhneorg** [comment]
JDT/ECJ is the compiler used by IBM/Eclipse. We have change the default compiler used by Maven for moving from javac to ecj. Indeed, ecj is much more better than javac for resolving generic types. If you are using an IDE that is not Eclipse, please ensure that is it using the JDT/ECJ, not javac.

**Comment by gallandarakhneorg** [comment]
Ok. I have also some issues on my side from the fresh clone. I will fix them asap.

**Comment by devFozgul** [comment]
I am now switching to Eclipse IDE. I am setting the project on  my laptop
as I will be using it while I am away from home for next week. Eclipse is
available on my laptop. In IntelliJ Idea I could easily incorporate
checkstyle.xml via Code Style settings. Is it the same with Eclipse. I have
never used Eclipse's checkstyle setting.
In Eclipse I am used to importing projects as Maven. So for JDT/ECJ, How do
I set Eclipse IDE?

**Comment by gallandarakhneorg** [comment]
In Eclipse, after import the AFC source code as Maven project, you may have a couple of errors. these errors could be easily solved by installing an Eclipse adapter (by clicking on the automatic problem solving option). Checkstyle has an Eclipse plugin that could be automatically installed in this way. You need to have Internet connexion.

**Comment by gallandarakhneorg** [comment]
I have pushed a code that seems to compile successfully on command line. Compilation results by our CI server are available on [Travis](https://travis-ci.org/gallandarakhneorg/afc/builds/136152553).

**Comment by devFozgul** [comment]
Ok. I will try again.

**Pull request closed without merging**
