### PR TITLE
Fixing squid:MethodCyclomaticComplexity Methods should not be too complex part 2

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:MethodCyclomaticComplexity - “""Methods should not be too complex”. 
 You can find more information about the issue here:
This PR will remove 41 min of TD. 
 https://dev.eclipse.org/sonar/rules/show/squid:MethodCyclomaticComplexity
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by gallandarakhneorg** [comment]
This PR does not provide an efficient code.
Indeed, creating a Map and searching inside has an average complexity of O(k/n).
A solution should be to put the default value in an attribute of each enumeration constant.

A similar job was done for the string representation of the types: see commit f77896e92cb2b203b1b96b3dbe398d86cfab6a4f.

**Comment by devFozgul** [comment]
I'll have a look at it again.

**Comment by gallandarakhneorg** [comment]
Don't worry. I have merged your contribution and fix the issue.

**Comment by devFozgul** [comment]
Thanks a lot.

**Pull request merged**
